# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CcKQVhE5f0Pq-DIot1pslTNCVe0hOtGA

This is the course era assignment week 1
"""

import pandas as pd
import numpy as np
print("Hello Capstone Project Course!")